config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "signup", to: "users#new"
  post "signup", to: "users#create"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users, only: [ :index ] do
    member do
      delete :destroy_account
    end

    resources :messages, only: [ :index, :create ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  belongs_to :reply_to, class_name: "Message", optional: true
  has_many :replies, class_name: "Message", foreign_key: :reply_to_id

  has_one_attached :file

  validates :content, presence: { message: "не может быть пустым" }, unless: -> { file.attached? },
            length: { minimum: 1, maximum: 1024,
                      too_short: "слишком короткое (мин. %{count} символ)",
                      too_long: "слишком длинное (макс. %{count} символов)", }

  scope :between, ->(a_id, b_id) {
    where(sender_id: [a_id, b_id], receiver_id: [a_id, b_id]).order(:created_at)
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false
  validates :username, presence: { message: "не может быть пустым" },
            uniqueness: { message: "уже занят" },
            length: { minimum: 2, maximum: 20,
                      too_short: "слишком короткое (мин. %{count} символа)",
                      too_long: "слишком длинное (макс. %{count} символов)" },
            format: { with: /\A[a-zA-Z0-9]+\Z/,
                      message: "может содержать только латинские буквы, цифры и _" }
  validates :password, presence: { message: "не может быть пустым" },
            length: { minimum: 8, maximum: 48,
                      too_short: "слишком короткий (мин. %{count} символов)",
                      too_long: "слишком длинный (макс. %{count} символов)" },
            confirmation: { message: "и подтверждение не совпадают" },
            if: -> { new_record? || !password.nil? }

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id", dependent: :destroy

  before_create :assign_random_avatar

  def online?
    last_login_at.present? && last_login_at > 3.minutes.ago
  end

  private

  def assign_random_avatar
    avatars = Dir[Rails.root.join("app/assets/images/avatars/*.png")]
    self.avatar = "avatars/#{File.basename(avatars.sample)}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    redirect_to login_path, alert: "Сначала нужно войти" unless logged_in?
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login

  def index
    @other = User.find(params[:user_id])
    @messages = Message.between(current_user.id, @other.id)
    @message = Message.new(reply_to_id: params[:reply_to])
  end

  def create
    @other = User.find(params[:user_id])
    @message = current_user.sent_messages.build(message_params)
    @message.receiver = @other
    if @message.save
      redirect_to user_messages_path(@other)
    else
      @messages = Message.between(current_user.id, @other.id)
      render :index, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :reply_to_id, :file)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      user.update(last_login_at: Time.current)
      session[:user_id] = user.id
      redirect_to users_path, notice: "Вход выполнен"
    else
      flash.now[:alert] = "Неверный логин или пароль"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Вы вышли"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [ :index,  :destroy_account]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path, notice: "Аккаунт создан"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def destroy_account
    @user = User.find(params[:id])
    if @user == current_user
      @user.destroy
      reset_session
      redirect_to signup_path, notice: "Ваш аккаунт удалён."
    else
      redirect_to users_path, alert: "Вы не можете удалить чужой аккаунт!"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
  def formatted_time(message)
    message.created_at.strftime("%d.%m.%Y %H:%M")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test Chat App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
        body { font-family: sans-serif; margin: 20px; }
        header { margin-bottom: 20px; }
        .messages { border: 1px solid #ccc; padding: 10px; max-width: 600px; }
        .message { margin-bottom: 10px; padding: 5px; border-bottom: 1px solid #eee; }
        .reply { font-size: 0.9em; color: #555; margin-left: 15px; }
        textarea { width: 100%; }
    </style>
  </head>

  <body>
  <header>
    <div class="app">
      <span class="app-icon">✆</span>
      <h1 class="app-title">Simple Chat App</h1>
      <small class="app-desc">Простое приложение для переписки</small>
    </div>

    <div class = "header-two">
      <% if logged_in? %>
        Привет, <%= current_user.username %> |
        <%= link_to "Пользователи", users_path, class: "panel-title" %> |
        <%= button_to "Выйти", logout_path, method: :delete, class: "btn btn-sm", style: "float: left" %>
        <%= button_to "Удалить мой аккаунт", destroy_account_user_path(current_user),
                      method: :delete,
                      form: { data: { turbo_confirm: "Вы точно хотите удалить свой аккаунт? Это действие нельзя отменить." } },
                      class: "btn btn-sm",
                      style: "background-color:#ffcccc; border-color:#ff0000;" %>
    <% else %>
        <%= link_to "Войти", login_path, class: "btn btn-sm" %> |
        <%= link_to "Регистрация", signup_path, class: "btn btn-sm" %>
      <% end %>
    </div>
  </header>

  <% if flash[:notice] %><p style="color:#015562;"><%= flash[:notice] %></p><% end %>

  <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Чат с <%= @other.username%></h1>

<div class="chat-top-bar">
  <%= link_to "⬅ К списку пользователей", users_path, class: "btn" %>
  <%= link_to "Обновить", user_messages_path(@other), class: "btn" %>
</div>

<section class="chat-panel">
  <div class="chat-messages" >
    <% @messages.each do |m| %>
      <p>
        <%= image_tag(m.sender.avatar || "avatars/default.png",
                      style: "border-color: #{['#FF0000','#00FF00','#0000FF','#FFA500'].sample};",
                      class: "user-avatar") %>
        <strong><%= m.sender.username %></strong>

        <% if m.sender.last_login_at.present? %>
          <% if m.sender.online? %>
            <small style="color:green; font-weight:bold;">● онлайн</small><br>
          <% else %>
            <small style="color:#666;">последний вход: <%= l m.sender.last_login_at, format: :short %></small><br>
          <% end %>
        <% else %>
          <small style="color:#999;">никогда не был в сети</small><br>

        <% end %>
        <%= m.content %>

        <% if m.file.attached? %>
          <br>
          <% if m.file.image? %>
            <%= link_to url_for(m.file), target: "_blank" do %>
              <%= image_tag m.file, style: "max-width: 200px; display: block; margin-top: 5px; border:1px solid #ccc; border-radius:4px;" %>
            <% end %>
          <% elsif m.file.content_type.start_with?('audio') %>
            <audio controls style="margin-top: 5px;">
              <source src="<%= url_for(m.file) %>" type="<%= m.file.content_type %>">
              Ваш браузер не поддерживает аудио.
            </audio>
          <% elsif m.file.content_type.start_with?('video') %>
            <video controls style="max-width: 300px; display: block; margin-top: 5px; border:1px solid #ccc; border-radius:4px;">
              <source src="<%= url_for(m.file) %>" type="<%= m.file.content_type %>">
              Ваш браузер не поддерживает видео.
            </video>
          <% else %>
            📎 <%= link_to m.file.filename, url_for(m.file) %>
          <% end %>
        <% end %>

        <% if m.reply_to.present? %>
          <br><small>↳ В ответ на: <%= truncate(m.reply_to.content, length: 30) %></small>
        <% end %>
        <br><small><%= formatted_time(m) %></small>
        <%= link_to "Ответить", user_messages_path(@other, reply_to: m.id), class: "btn btn-sm", style: "float: right" %>
      </p>
    <% end %>
  </div>

  <%= form_with model: [@other, @message], local: true do |f| %>
    <%= f.hidden_field :reply_to_id %>
    <p>
      <%= f.label :content, "Сообщение" %><br>
      <%= f.text_area :content, style: "height: 80px" %>
      <% if @message.errors[:content].any? %>
      <div class="error"><%= @message.errors[:content].first %></div>
    <% end %>



    <div class = "send-block">
    <p><%= f.submit "Отправить", class: "btn" %>
      <% if @message.reply_to_id.present? %> <%= link_to "Отменить ответ", user_messages_path(@other), class: "btn btn-sm" %> <% end %>
      <p>
        <label class="btn" style="position: relative;">
          📎 Прикрепить файл
          <%= f.file_field :file, style: "display: none;",
                           onchange: "this.nextElementSibling.innerText = this.files[0]?.name || 'Файл не выбран'" %>
          <span class="filename" style="margin-left: 10px; font-size: 12px; color: #555;">Файл не выбран</span>
        </label>
      </p>
    </div>
  <% end %>
</section>

app/views/users/index.html.erb
<h1>Пользователи</h1>

<ul>
  <% @users.each do |user| %>
    <% next if user == current_user %>
    <li style="margin-bottom:8px;">
      <%= image_tag(user.avatar || "avatars/default.png", style: "border-color: #{['#FF0000','#00FF00','#0000FF','#FFA500'].sample};", class: "user-avatar") %>
      <%= link_to user.username, user_messages_path(user), class: "btn" %>

      <% if user.last_login_at.present? %>
        <% if user.online? %>
          <span style="color:#0095b7; font-weight:bold; margin-left:8px;">● онлайн</span>
        <% else %>
          <small style="color:#666; margin-left:8px;">
            последний вход: <%= l user.last_login_at, format: :short %>
          </small>
        <% end %>
      <% else %>
        <small style="color:#999; margin-left:8px;">никогда не был в сети</small>
      <% end %>

    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_with model: @user, url: signup_path, local: true do |f| %>
  <p>
    <%= f.label :username, "Имя пользователя" %><br>
    <%= f.text_field :username, size: 30 %>
    <% if @user.errors[:username].any? %>
      <div class="error"><%= @user.errors[:username].first %></div>
    <% end %>
  </p>

  <p>
    <%= f.label :password, "Пароль" %><br>
    <%= f.password_field :password, size: 30 %>
    <% if @user.errors[:password].any? %>
      <div class="error"><%= @user.errors[:password].first %></div>
    <% end %>
  </p>

  <p>
    <%= f.label :password_confirmation, "Подтверждение пароля" %><br>
    <%= f.password_field :password_confirmation, size: 30 %>
    <% if @user.errors[:password_confirmation].any? %>
      <div class="error"><%= @user.errors[:password_confirmation].first %></div>
    <% end %>
  </p>

  <p><%= f.submit "Зарегистрироваться", class: "btn" %></p>
<% end %>